# Board
NUMBER_SPACES = 20
MIN_REAL_STATE_PRICE = 50
MAX_REAL_STATE_PRICE = 150
MIN_REAL_STATE_RENT_PERCENTAGE = 10
MAX_REAL_STATE_RENT_PERCENTAGE = 50

# Dice
NUMBER_FACES = 6

# Game
MAX_ROUNDS = 1000
AROUND_BOARD_BONUS = 100

# Players
INITIAL_AMOUNT = 300

# simulation
SIMULATIONS_QUANTITY = 200
